// -- Sequências de escape para as cores no console
#if ENABLE_COLORS
#define TERM_BOLD_BLACK		"\033[1;30m"
#define TERM_BOLD_RED		"\033[1;31m"
#define TERM_BOLD_GREEN		"\033[1;32m"
#define TERM_BOLD_YELLOW	"\033[1;33m"
#define TERM_BOLD_MAGENTA	"\033[1;35m"
#define TERM_BOLD_CYAN		"\033[1;36m"
#define TERM_BOLD_WHITE		"\033[1;37m"
#define TERM_RED			"\033[0;31m"
#define TERM_GREEN			"\033[32m"
#define TERM_YELLOW			"\033[33m"
#define TERM_MAGENTA		"\033[0;35m"
#define TERM_CYAN			"\033[0;36m"
#define TERM_WHITE			"\033[37m"
#define TERM_RESET			"\033[0m"
#else
#define TERM_BOLD_BLACK		""
#define TERM_BOLD_RED		""
#define TERM_BOLD_GREEN		""
#define TERM_BOLD_YELLOW	""
#define TERM_BOLD_MAGENTA	""
#define TERM_BOLD_CYAN		""
#define TERM_BOLD_WHITE		""
#define TERM_RED			""
#define TERM_GREEN			""
#define TERM_YELLOW			""
#define TERM_MAGENTA		""
#define TERM_CYAN			""
#define TERM_RESET			""
#endif